### ISSUE TITLE
Bug with message passing models

### ISSUE THREAD

**Issue by nicolas-chaulet** [nicolas-chaulet/deeppointcloud-benchmarks#130]
Models based on message passing fail in the radius search for some strange reason:
```
/pytorch/aten/src/THC/THCTensorScatterGather.cu:160: void THCudaTensor_scatterAddKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = long, Dims = 1]: block: [0,0,0], thread: [319,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.
  0%|                                                                                                                                                                          | 0/7004 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 156, in <module>
    main()
  File "/home/tristan/.conda/envs/pdalenv/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
 <...>
  File "/home/tristan/deeppointcloud-benchmarks/src/core/base_conv/message_passing.py", line 64, in forward
    row, col = self.neighbour_finder(pos, pos[idx], batch_x=batch, batch_y=batch[idx])
  File "/home/tristan/deeppointcloud-benchmarks/src/core/neighbourfinder/neighbour_finder.py", line 16, in __call__
    return self.find_neighbours(x, y, batch_x, batch_y)
  File "/home/tristan/deeppointcloud-benchmarks/src/core/neighbourfinder/neighbour_finder.py", line 33, in find_neighbours
    return radius(x, y, self._radius, batch_x, batch_y, max_num_neighbors=self._max_num_neighbors)
  File "/home/tristan/.conda/envs/pdalenv/lib/python3.6/site-packages/torch_cluster/radius.py", line 61, in radius
    max_num_neighbors)
RuntimeError: scan failed to synchronize: device-side assert triggered
```

**Comment by tchaton** [comment]
@nicolas-chaulet , it seems to come from FPS.

I have added a test with a warning within the test: https://github.com/nicolas-chaulet/deeppointcloud-benchmarks/pull/144

**Comment by nicolas-chaulet** [comment]
Looks good now
